### ISSUE TITLE
Portable Item Nullifier bypasses FTBU claims

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-Expert#13]
Non-OP players are able to place blocks in "protected" FTBU claimed chunks with the Portable Item Nullifier.

I'll report this to both nullifiers and ftbu trackers but making a note here to recommend setting `B:"Enable Portable Item Nullifier (recipe)"=false` in "usefulnullifiers.cfg" until a proper fix is released in one or both mods.

**Comment by OrdinatorStouff** [comment]
FTBU Issue: https://github.com/Bartz24/UsefulNullifiers/issues/10
Useful Nullifiers Issue: https://github.com/LatvianModder/FTBUtilities/issues/384

**Comment by Bartz24** [comment]
Wait, are you sure it's the portable item nullifier? The portable _overflow_ nullifier is the one that can place blocks.

**Comment by OldDogy** [comment]
It's the item that can keep a stack of assigned items in it, voids everything above that amount and can place down those blocks with right-click.

The item also overrides "spwan-protection" ; Ignores that blocks you look at is liquid source and places a solid block above the water source block instead of replacing the liquid source block.
From what I know it's ignoring every type of protection.

**Comment by OrdinatorStouff** [comment]
Need to follow-up and see if this is still a problem in pack version 1.1.1+ or not

Also I would like to test if the FTBU ranks "right click inside claims" node denial can prevent this
