### ISSUE TITLE
Penance ritual disabled

### ISSUE THREAD

**Issue by weisspure** [AllTheMods/ATM-Expert#8]
The penance ritual for weakened pick from blood magic requires a stone pickaxe which is disabled, I'd suggest either including an expensive recipe for a stone pickaxe or altering the penance ritual recipe to not include the stone pickaxe.
![2017-03-08_00 55 20](https://cloud.githubusercontent.com/assets/26007794/23685050/fd41429e-0399-11e7-8b4d-9480ff4f1563.png)

**Comment by OrdinatorStouff** [comment]
Stone pick is really only disabled to prevent spamming "easy" picks after first flint.

Help wanted: I also wonder if this penance ritual will accept a damaged stone pick or if it has to be "full" value as I can add a simple recipe for a pick that has only 1 durability left.

Otherwise just making it require treated sticks should be far more than adequate of a "gate"

**Comment by BloodWorkXGaming** [comment]
With crafttweaker you can set a Max durability on items. Therefore you can set the durability to 1 but is still is "full".
