### ISSUE TITLE
Bee quest book issue

### ISSUE THREAD

**Issue by Ravalli03** [AllTheMods/ATM-Expert#97]
When trying to progress with the Gendusty template with the 2 traits added to it, it doesn't recognize it. I have tried everything including cheating in items.

**Comment by goosezilla** [comment]
cant reproduce the issue

**Comment by Ravalli03** [comment]
Hmm, werid, will try it again, and if I understand right it's a template with just those 2 traits added to it on a crafting table

**Comment by goosezilla** [comment]
Which quest are you doing?

**Comment by Ravalli03** [comment]
It was the "Genetic Templates" from Chapter 12, but for whatever reason it worked this time around. I'm not sure what/if I was doing something wrong last night. Only thing I did different was, when I crafted it the first time, I didn't add them both to the template at the same crafting session, ie added 1, then added the second.  I'll leave it up to you to close this, as if the above statement is true, maybe others may have the same issue.  

Thanks for the quick reply and the pack!

**Comment by goosezilla** [comment]
There are 2 separate quests with one trait on each template rather than 2 traits on 1, I think thats where you were going wrong.

**Comment by tloskpd** [comment]
I actually ran into this issue as well when i added the genes to the template for the Genetic Templates quest.  And goose, there is no 2 separate quests for the traits on templates.  It wants you to get those 2 traits on gene samples.  The follow-up quest wants both those traits on the gene sample to complete.  

But based on my testing, the quest will only "complete" if you add the traits in a specific order as they are written in the HQM config file.  The config is looking for, in order, shortest lifespan than fertility 4 in the NBT tag in order to complete.  There can be no other chromosomes  as well for the quest to complete.  I've tried adding the genes in reverse order, and HQM would not detect as complete, and depending on the order added to shapeless crafting window, you can add both at the same times as long as shortest lifespan was added first.

This was all on 1.1.1 running on a local private server, and even in single player test world.
